/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{633:function(ya,va,r){r.r(va);var la=r(0),na=r(1);r.n(na);var ma=r(2),ja=r(220);ya=r(53);var ia=r(129),ca=r(367),y=r(107),x=r(366);r=r(547);var n=window,h=function(){function f(a,w,z){var aa=-1===a.indexOf("?")?"?":"&";switch(w){case y.a.NEVER_CACHE:this.url="".concat(a+aa,"_=").concat(Object(na.uniqueId)());break;default:this.url=a}this.Sf=z;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=x.a.NOT_STARTED}f.prototype.start=function(a,w){var z=this,aa=this,ea=this.request,ba;aa.FF=0;a&&Object.keys(a).forEach(function(fa){z.request.setRequestHeader(fa,a[fa])});w&&(this.request.withCredentials=w);this.yO=setInterval(function(){var fa=0===window.document.URL.indexOf("file:///");fa=200===ea.status||
fa&&0===ea.status;if(ea.readyState!==x.b.DONE||fa){try{ea.responseText}catch(ha){return}aa.FF<ea.responseText.length&&(ba=aa.RMa())&&aa.trigger(f.Events.DATA,[ba]);0===ea.readyState&&(clearInterval(aa.yO),aa.trigger(f.Events.DONE))}else clearInterval(aa.yO),aa.trigger(f.Events.DONE,["Error received return status ".concat(ea.status)])},1E3);this.request.send(null);this.status=x.a.STARTED};f.prototype.RMa=function(){var a=this.request,w=a.responseText;if(0!==w.length)if(this.FF===w.length)clearInterval(this.yO),
this.trigger(f.Events.DONE);else return w=Math.min(this.FF+3E6,w.length),a=n.raa(a,this.FF,!0,w),this.FF=w,a};f.prototype.abort=function(){clearInterval(this.yO);var a=this;this.request.onreadystatechange=function(){Object(ma.i)("StreamingRequest aborted");a.status=x.a.ABORTED;return a.trigger(f.Events.ABORTED)};this.request.abort()};f.prototype.finish=function(){var a=this;this.request.onreadystatechange=function(){a.status=x.a.SUCCESS;return a.trigger(f.Events.DONE)};this.request.abort()};f.Events=
{DONE:"done",DATA:"data",ABORTED:"aborted"};return f}();Object(ya.a)(h);var b;(function(f){f[f.LOCAL_HEADER=0]="LOCAL_HEADER";f[f.FILE=1]="FILE";f[f.CENTRAL_DIR=2]="CENTRAL_DIR"})(b||(b={}));var e=function(f){function a(){var w=f.call(this)||this;w.buffer="";w.state=b.LOCAL_HEADER;w.F0=4;w.Hq=null;w.FA=ja.c;w.Rs={};return w}Object(la.c)(a,f);a.prototype.DMa=function(w){var z;for(w=this.buffer+w;w.length>=this.FA;)switch(this.state){case b.LOCAL_HEADER:this.Hq=z=this.WMa(w.slice(0,this.FA));if(z.sB!==
ja.g)throw Error("Wrong signature in local header: ".concat(z.sB));w=w.slice(this.FA);this.state=b.FILE;this.FA=z.iT+z.Fw+z.ZD+this.F0;this.trigger(a.Events.HEADER,[z]);break;case b.FILE:this.Hq.name=w.slice(0,this.Hq.Fw);this.Rs[this.Hq.name]=this.Hq;z=this.FA-this.F0;var aa=w.slice(this.Hq.Fw+this.Hq.ZD,z);this.trigger(a.Events.FILE,[this.Hq.name,aa,this.Hq.KT]);w=w.slice(z);if(w.slice(0,this.F0)===ja.h)this.state=b.LOCAL_HEADER,this.FA=ja.c;else return this.state=b.CENTRAL_DIR,!0}this.buffer=w;
return!1};a.Events={HEADER:"header",FILE:"file"};return a}(ca.a);Object(ya.a)(e);ya=function(f){function a(w,z,aa,ea,ba){aa=f.call(this,w,aa,ea)||this;aa.url=w;aa.stream=new h(w,z);aa.$e=new e;aa.Wea=window.createPromiseCapability();aa.Nfa={};aa.Sf=ba;return aa}Object(la.c)(a,f);a.prototype.NG=function(w){var z=this;this.request([this.cn,this.kp,this.bn]);this.stream.addEventListener(h.Events.DATA,function(aa){try{if(z.$e.DMa(aa))return z.stream.finish()}catch(ea){throw z.stream.abort(),z.Lv(ea),
w(ea),ea;}});this.stream.addEventListener(h.Events.DONE,function(aa){z.XLa=!0;z.Wea.resolve();aa&&(z.Lv(aa),w(aa))});this.$e.addEventListener(e.Events.HEADER,Object(na.bind)(this.Mfa,this));this.$e.addEventListener(e.Events.FILE,Object(na.bind)(this.nNa,this));return this.stream.start(this.Sf,this.withCredentials)};a.prototype.jaa=function(w){var z=this;this.Wea.promise.then(function(){w(Object.keys(z.$e.Rs))})};a.prototype.Tt=function(){return!0};a.prototype.request=function(w){var z=this;this.XLa&&
w.forEach(function(aa){z.Nfa[aa]||z.QUa(aa)})};a.prototype.Mfa=function(){};a.prototype.abort=function(){this.stream&&this.stream.abort()};a.prototype.QUa=function(w){this.trigger(ia.a.Events.PART_READY,[{Qb:w,error:"Requested part not found",Yl:!1,Bi:!1}])};a.prototype.nNa=function(w,z,aa){this.Nfa[w]=!0;this.trigger(ia.a.Events.PART_READY,[{Qb:w,data:z,Yl:!1,Bi:!1,error:null,Ie:aa}])};return a}(ia.a);Object(r.a)(ya);Object(r.b)(ya);va["default"]=ya}}]);}).call(this || window)
